FrontEnd/app/home/__init__.py
<<<<<<< HEAD
# application/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

=======
# application/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

>>>>>>> 270786ff41f19b6230c41b27351db543564b1c60
from . import views

FrontEnd/app/home/views.py
<<<<<<< HEAD
# application/home/views.py

from flask import render_template, Response, abort
from flask_login import login_required, current_user
from . import home
import ast

from ..socket_client_side import simple_receive, video_receive


@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    try:
        table_data = simple_receive().decode('utf-8')
        table_data = ast.literal_eval(table_data[1:-1])
    except ConnectionRefusedError as error:
        table_data = {}
    finally:
        return render_template('home/dashboard.html', title="Dashboard", table_output=table_data)


@home.route('/video_feed')
@login_required
def video_feed():
    try:
        return Response(video_receive(), mimetype='multipart/x-mixed-replace; boundary=frame')
    except ConnectionError:
        return render_template('errors/502.html', title="image")

=======
# application/home/views.py

from flask import render_template, Response, abort
from flask_login import login_required, current_user
from . import home
import ast

from ..socket_client_side import simple_receive, video_receive


@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    try:
        table_data = simple_receive().decode('utf-8')
        table_data = ast.literal_eval(table_data[1:-1])
    except ConnectionRefusedError as error:
        table_data = {}
    finally:
        return render_template('home/dashboard.html', title="Dashboard", table_output=table_data)


@home.route('/video_feed')
@login_required
def video_feed():
    try:
        return Response(video_receive(), mimetype='multipart/x-mixed-replace; boundary=frame')
    except ConnectionError:
        return render_template('errors/502.html', title="image")

>>>>>>> 270786ff41f19b6230c41b27351db543564b1c60

FrontEnd/templates/home/admin_dashboard.html
<<<<<<< HEAD
<!-- application/templates/home/admin_dashboard.html -->

{% extends "/home/dashboard.html" %}
{% block title %}Admin Dashboard{% endblock %}
{% block body %}
    {{ super() }}
=======
<!-- application/templates/home/admin_dashboard.html -->

{% extends "/home/dashboard.html" %}
{% block title %}Admin Dashboard{% endblock %}
{% block body %}
    {{ super() }}
>>>>>>> 270786ff41f19b6230c41b27351db543564b1c60
{% endblock %}

FrontEnd/templates/home/dashboard.html
<<<<<<< HEAD
<!-- application/templates/home/dashboard.html -->

{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
    <script src="{{ url_for('static' , filename='script/custom.min.js') }}"></script>
{% endblock %}

{% block body %}

    <div id="Sidebar" class="w3-sidebar w3-bar-block w3-card w3-animate-right bg-dark"
         style="display:none;right:0">
        <div>
            <button class="w3-bar-item w3-button font-weight-bold"
                    onclick="sidebar_close()">Close &times;
            </button>
            <div class="dropdown-divider"></div>

            <div id="SideBarSmartParking" class="pos-f-t">
                <button class="w3-bar-item w3-button font-weight-normal" type="button"
                        data-toggle="collapse"
                        data-target="#SmartParking" aria-controls="navbarToggleExternalContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="">smart Parking</span>
                </button>

                <div class="collapse w3-animate-right" id="SmartParking">
                    <div class="bg-dark pr-4">
                        <a href="#" class="w3-bar-item w3-button font-weight-light">Slot Initializer</a>
                        <a href="#" class="w3-bar-item w3-button font-weight-light">Slot Detector</a>
                        <a href="#" class="w3-bar-item w3-button font-weight-light">Plate Reader</a>
                    </div>
                </div>
            </div>
            <div id="SidebarDetectionSystem" class="pos-f-t">
                <button class="w3-bar-item w3-button font-weight-normal " type="button"
                        data-toggle="collapse"
                        data-target="#DetectionSystem" aria-controls="navbarToggleExternalContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="">Human detection</span>
                </button>

                <div class="collapse w3-animate-right" id="DetectionSystem">
                    <div class="bg-dark pr-4">
                        <a href="#" class="w3-bar-item w3-button font-weight-light">Control Access Initializer</a>

                        <a href="#" class="w3-bar-item w3-button font-weight-light">Control Access</a>
                    </div>
                </div>
            </div>
            <div id="SidebarOCR" class="pos-f-t">
                <button class="w3-bar-item w3-button font-weight-normal " type="button"
                        data-toggle="collapse"
                        data-target="#OCR" aria-controls="navbarToggleExternalContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="">OCR</span>
                </button>

                <div class="collapse w3-animate-right" id="OCR">
                    <div class="bg-dark pr-4">
                        <a href="#" class="w3-bar-item w3-button font-weight-light">Character reading</a>

                        <a href="#" class="w3-bar-item w3-button font-weight-light">Translate</a>
                    </div>
                </div>
            </div>
            <a href="#" class="w3-bar-item w3-button font-weight-normal">API</a>
        </div>

    </div>

    <div id="main">
        <div class="row d-flex flex-row-reverse">
            <div id="sideMenu" class="">
                <button id="openNav" class=" navbar-dark bg-dark navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                        aria-expanded="false" aria-label="Toggle navigation" onclick="sidebar_open()">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>

            <div id="container" class="col-12" align="center">
                <div class="container-fluid">
                    <div class="row align-content-center">
                        <div id="video_section" class="col-md-7 align-content-center" align="center">
                            <h1 style="text-align:center;">Video Feed</h1>
                            <hr class="intro-divider">
                            <img id="video_feed" class="img-fluid rounded mx-auto d-block"
                                 src="{{ url_for('home.video_feed') }}" alt="Error: Contact your administrator">
                        </div>
                        <div id="table_section" class="col-md-5" align="center">
                            <h1 style="text-align:center;">previous events</h1>
                            <hr class="intro-divider">
                            <table id="event_table"
                                   class="table table-striped table-hover table-borderless table-responsive-sm"
                                   align="center">
                                <thead class="thead-dark">
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Subject</th>
                                    <th scope="col">Direction</th>
                                    <th scope="col">Time</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for detected_item in table_output %}
                                    <tr class="bg-dark">
                                        <th scope="row">{{ loop.index }}</th>
                                        <td>{{ detected_item.subject }}</td>
                                        <td>{{ detected_item.direction }}</td>
                                        <td>{{ detected_item.time }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

=======
<!-- application/templates/home/dashboard.html -->

{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
    <script src="{{ url_for('static' , filename='script/custom.min.js') }}"></script>
{% endblock %}

{% block body %}

    <div id="Sidebar" class="w3-sidebar w3-bar-block w3-card w3-animate-right bg-dark"
         style="display:none;right:0">
        <div>
            <button class="w3-bar-item w3-button font-weight-bold"
                    onclick="sidebar_close()">Close &times;
            </button>
            <div class="dropdown-divider"></div>

            <div id="SideBarSmartParking" class="pos-f-t">
                <button class="w3-bar-item w3-button font-weight-normal" type="button"
                        data-toggle="collapse"
                        data-target="#SmartParking" aria-controls="navbarToggleExternalContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="">smart Parking</span>
                </button>

                <div class="collapse w3-animate-right" id="SmartParking">
                    <div class="bg-dark pr-4">
                        <a href="#" class="w3-bar-item w3-button font-weight-light">Slot Initializer</a>
                        <a href="#" class="w3-bar-item w3-button font-weight-light">Slot Detector</a>
                        <a href="#" class="w3-bar-item w3-button font-weight-light">Plate Reader</a>
                    </div>
                </div>
            </div>
            <div id="SidebarDetectionSystem" class="pos-f-t">
                <button class="w3-bar-item w3-button font-weight-normal " type="button"
                        data-toggle="collapse"
                        data-target="#DetectionSystem" aria-controls="navbarToggleExternalContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="">Human detection</span>
                </button>

                <div class="collapse w3-animate-right" id="DetectionSystem">
                    <div class="bg-dark pr-4">
                        <a href="#" class="w3-bar-item w3-button font-weight-light">Control Access Initializer</a>

                        <a href="#" class="w3-bar-item w3-button font-weight-light">Control Access</a>
                    </div>
                </div>
            </div>
            <div id="SidebarOCR" class="pos-f-t">
                <button class="w3-bar-item w3-button font-weight-normal " type="button"
                        data-toggle="collapse"
                        data-target="#OCR" aria-controls="navbarToggleExternalContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="">OCR</span>
                </button>

                <div class="collapse w3-animate-right" id="OCR">
                    <div class="bg-dark pr-4">
                        <a href="#" class="w3-bar-item w3-button font-weight-light">Character reading</a>

                        <a href="#" class="w3-bar-item w3-button font-weight-light">Translate</a>
                    </div>
                </div>
            </div>
            <a href="#" class="w3-bar-item w3-button font-weight-normal">API</a>
        </div>

    </div>

    <div id="main">
        <div class="row d-flex flex-row-reverse">
            <div id="sideMenu" class="">
                <button id="openNav" class=" navbar-dark bg-dark navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                        aria-expanded="false" aria-label="Toggle navigation" onclick="sidebar_open()">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>

            <div id="container" class="col-12" align="center">
                <div class="container-fluid">
                    <div class="row align-content-center">
                        <div id="video_section" class="col-md-7 align-content-center" align="center">
                            <h1 style="text-align:center;">Video Feed</h1>
                            <hr class="intro-divider">
                            <img id="video_feed" class="img-fluid rounded mx-auto d-block"
                                 src="{{ url_for('home.video_feed') }}" alt="Error: Contact your administrator">
                        </div>
                        <div id="table_section" class="col-md-5" align="center">
                            <h1 style="text-align:center;">previous events</h1>
                            <hr class="intro-divider">
                            <table id="event_table"
                                   class="table table-striped table-hover table-borderless table-responsive-sm"
                                   align="center">
                                <thead class="thead-dark">
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Subject</th>
                                    <th scope="col">Direction</th>
                                    <th scope="col">Time</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for detected_item in table_output %}
                                    <tr class="bg-dark">
                                        <th scope="row">{{ loop.index }}</th>
                                        <td>{{ detected_item.subject }}</td>
                                        <td>{{ detected_item.direction }}</td>
                                        <td>{{ detected_item.time }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

>>>>>>> 270786ff41f19b6230c41b27351db543564b1c60
{% endblock %}

FrontEnd/templates/home/index.html
<<<<<<< HEAD
<!-- application/templates/home/index.html -->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
    <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <br/>
                        <br/>
                        <h1>Raahbar Informatics Services Company</h1>
                        <h3>The best company in the world!</h3>
                        <hr class="intro-divider">
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
=======
<!-- application/templates/home/index.html -->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
    <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <br/>
                        <br/>
                        <h1>Raahbar Informatics Services Company</h1>
                        <h3>The best company in the world!</h3>
                        <hr class="intro-divider">
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
>>>>>>> 270786ff41f19b6230c41b27351db543564b1c60